### ISSUE TITLE
SlitScan node

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/openfx-misc#29]
A slitscan node that permits:
- traditional slitscan a la Douglas Trumbull
- per-pixel retiming using an optional retime map

Parameters would be gain and offset for the retime map, an "absolute" ckeckbox, and a frame range (automatically set when the default vertical ramp is used as the retime map)

A placeholder plugin is in the SlitScan directory

**Comment by manuelsongokuh** [comment]
what is will be milestone for SlitScan node?

**Comment by devernay** [comment]
done!

**Comment by manuelsongokuh** [comment]
WOOOOW.. i wish try it!
