### ISSUE TITLE
DenoiseSharpen

### ISSUE THREAD

**Issue by maximoremedios** [NatronGitHub/openfx-misc#47]
Hi there! 
Just used DenoiseSharpen today for the first time, wow, excellent! I don't know if I'm in the right place to post suggestions but if so, may I suggest some developments? 
- the ability to visually see next to each other the luminance, the chrominance channels (Cb, Cr) and the denoised footage.
- the ability to see high, mid, and low frequencies in each frequency components (Y, Cb, Cr). Ideally a quad view with the denoised/sharpened result on top left or right corner + black and white views of high, mid, and low frequencies.
- when changing a value in any of the settings, a before and after toggle visualisation.

Many thanks

**Comment by devernay** [comment]
you should be able to get the before and after toggle with cmd-Z or ctrl-Z. All other suggestions would take time to implement...
