### ISSUE TITLE
cimg makefile does not use c++11

### ISSUE THREAD

**Issue by 3dsman** [NatronGitHub/openfx-misc#58]
it leads to errors like those:
./CImg.h:5333:14: error: ‘log2’ is not a member of ‘std’
       return std::log2(x);
./CImg.h:5319:14: error: ‘atanh’ is not a member of ‘std’
       return std::atanh(x);
./CImg.h:5310:14: error: ‘asinh’ is not a member of ‘std’
       return std::asinh(x);

it can be fixed by adding this line into CImg/Makefile
CXXFLAGS += -std=c++11

**Comment by 3dsman** [comment]
I use gcc on my linux mint install which return:
__cplusplus=199711

but this version can compile c++11 command with the "-std=c++11" option and then, the same code return:
__cplusplus=201103

This is effectively strange but it seem other compilers have the same behaviour (vc++) for compatibility purpose
It seem checking __cplusplus value is not a very reliable test to check for c++11 compatibility

**Comment by devernay** [comment]
But if you look at the cimg.h code, you will see that it should compile
fine without c++11. Can you please give the compile line and the list of
errors/warnings?

**Comment by 3dsman** [comment]
make[1] : on entre dans le répertoire « /home/seb/builds/my_natron/openfx-misc/CImg »
  CXX      Linux-64-debug/CImgBilateral.o
In file included from ./CImgFilter.h:164:0,
                 from Bilateral/CImgBilateral.cpp:36:
./CImg.h: In function ‘double cimg_library_openfx_misc::cimg::acosh(double)’:
./CImg.h:5301:14: error: ‘acosh’ is not a member of ‘std’
       return std::acosh(x);
              ^
./CImg.h:5301:14: note: suggested alternatives:
In file included from /usr/include/features.h:367:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/os_defines.h:39,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/c++config.h:482,
                 from /usr/include/c++/5/bits/stl_algobase.h:59,
                 from /usr/include/c++/5/memory:62,
                 from Bilateral/CImgBilateral.cpp:23:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:88:1: note:   ‘acosh’
 __MATHCALL (acosh,, (_Mdouble_ __x));
 ^
In file included from ./CImgFilter.h:164:0,
                 from Bilateral/CImgBilateral.cpp:36:
./CImg.h:5299:19: note:   ‘cimg_library_openfx_misc::cimg::acosh’
     inline double acosh(const double x) {
                   ^
./CImg.h: In function ‘double cimg_library_openfx_misc::cimg::asinh(double)’:
./CImg.h:5310:14: error: ‘asinh’ is not a member of ‘std’
       return std::asinh(x);
              ^
./CImg.h:5310:14: note: suggested alternatives:
In file included from /usr/include/features.h:367:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/os_defines.h:39,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/c++config.h:482,
                 from /usr/include/c++/5/bits/stl_algobase.h:59,
                 from /usr/include/c++/5/memory:62,
                 from Bilateral/CImgBilateral.cpp:23:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:90:1: note:   ‘asinh’
 __MATHCALL (asinh,, (_Mdouble_ __x));
 ^
In file included from ./CImgFilter.h:164:0,
                 from Bilateral/CImgBilateral.cpp:36:
./CImg.h:5308:19: note:   ‘cimg_library_openfx_misc::cimg::asinh’
     inline double asinh(const double x) {
                   ^
./CImg.h: In function ‘double cimg_library_openfx_misc::cimg::atanh(double)’:
./CImg.h:5319:14: error: ‘atanh’ is not a member of ‘std’
       return std::atanh(x);
              ^
./CImg.h:5319:14: note: suggested alternatives:
In file included from /usr/include/features.h:367:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/os_defines.h:39,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/c++config.h:482,
                 from /usr/include/c++/5/bits/stl_algobase.h:59,
                 from /usr/include/c++/5/memory:62,
                 from Bilateral/CImgBilateral.cpp:23:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:92:1: note:   ‘atanh’
 __MATHCALL (atanh,, (_Mdouble_ __x));
 ^
In file included from ./CImgFilter.h:164:0,
                 from Bilateral/CImgBilateral.cpp:36:
./CImg.h:5317:19: note:   ‘cimg_library_openfx_misc::cimg::atanh’
     inline double atanh(const double x) {
                   ^
./CImg.h: In function ‘double cimg_library_openfx_misc::cimg::log2(double)’:
./CImg.h:5333:14: error: ‘log2’ is not a member of ‘std’
       return std::log2(x);
              ^
./CImg.h:5333:14: note: suggested alternatives:
In file included from /usr/include/features.h:367:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/os_defines.h:39,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/c++config.h:482,
                 from /usr/include/c++/5/bits/stl_algobase.h:59,
                 from /usr/include/c++/5/memory:62,
                 from Bilateral/CImgBilateral.cpp:23:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:144:1: note:   ‘log2’
 __MATHCALL (log2,, (_Mdouble_ __x));
 ^
In file included from ./CImgFilter.h:164:0,
                 from Bilateral/CImgBilateral.cpp:36:
./CImg.h:5331:19: note:   ‘cimg_library_openfx_misc::cimg::log2’
     inline double log2(const double x) {
                   ^
../openfx/Support/Plugins/Makefile.master:82 : la recette pour la cible « Linux-64-debug/CImgBilateral.o » a échouée

**Comment by devernay** [comment]
Actually I wanted tio see the commandline, which can be seen using "make V=1".
Line 5301 (irst error) is the following code:
```
#if defined(cimg_use_cpp11) && !defined(_MSC_VER)
      return std::acosh(x); <--- 5301
#else
      return std::log(x + std::sqrt(x*x - 1));
#endif
```
This is a bug in this version of CImg.h. Everywhere in CImg.h, `defined(cimg_use_cpp11)`shoulde be replaced by `cimg_use_cpp11==1`

This was fixed later in CImg.h. You can fix this by testing with the latest released version (2.4.2)  of CImg.h which has commit cbf7372471f0593fa0315bf6db2b0adc9146d85b 

Change the commit ID in the Makefile to this one, delete CImg.h, and relauch make. This would download the 2.4.2 version
Alternatively, grab it from there: https://raw.githubusercontent.com/dtschump/CImg/cbf7372471f0593fa0315bf6db2b0adc9146d85b/CImg.h

Can you please tell me if you have no issues with the 2.4.2 version? in this case, I will spend some time this weekend to upgrade it on the repo

**Comment by yomgui1** [comment]
Confirmed with travis build: this one using clang 5.0.0 https://travis-ci.org/NatronGitHub/openfx-misc/jobs/530065930

This compiler needs -std=c++11 even with #include <cmath>
see https://gcc.godbolt.org/z/chxYFl

**Comment by yomgui1** [comment]
Note: I've checked __cpluscplus value for Clang 5.0.0, it's 199711
see https://gcc.godbolt.org/z/PxIEEg
The check in CImg.h should work. I don't see the reason yet
But the version used is quit old now. latest release of CImg.h is 2.6.1. Maybe it's fixed since.

**Comment by yomgui1** [comment]
I think that https://github.com/NatronGitHub/openfx-misc/pull/62 solves the problem... waiting for build and integration
