### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by fletchdp** [NatronGitHub/openfx-misc#67]
Hello.
It seems I'm unable to build latest openfx-misc on my Gentoo. I think the issue somewhere on this line:
if [ \( debug = "release" -o debug = "relwithdebinfo" \) -a Linux-x86-64 = "MacOS" ]; then bash ../openfx/Support/include/osxDeploy.sh Linux-64-debug/Misc.ofx.bundle Misc.ofx; fi
I'm attaching full build log.
Bash version is 4.4.23
[openfx-misc-build.log](https://github.com/NatronGitHub/openfx-misc/files/3397122/openfx-misc-build.log)

**Comment by rodlie** [comment]
Might be an issue with the ebuild(?). Try building it manually.

**Comment by fletchdp** [comment]
> Might be an issue with the ebuild(?). Try building it manually.

Text above is from openfx/Support/Plugins/Makefile.master
So I doubt it's an ebuild issue
I get same error trying to emerge openfx-misx-2.3.14_p20190709 version

**Comment by devernay** [comment]
I don't see an error there. It doesn't say that the command fails. "make" exits normally and then it says that the error comes from "emake", so I guess it is something in the gentoo script. Try executing "make" manually, you will see that you will get no error.
Closing this, as it is related to the gentoo build/packaging system.
