### ISSUE TITLE
Having issue compiling plugin with glext.h on MSVC (Windows 10)

### ISSUE THREAD

**Issue by yueda1984** [NatronGitHub/openfx-misc#70]
Hi, I am having issue compiling openfx-misc on MSVC. I noticed that devernay provided the precompiled misc.ofx.bundle but I want to compile some plugins individually so when I bring them to Toon Boom Harmony, the module library won't get so crowded with extra plugins.

First about, Noise.cpp and PluginRegistrationCombined.cpp that are present on Misc.vcxproj are no longer present on the repository. So I removed them from the project.

ColorLookup.cpp includes GL/glext.h which was not installed on my computer, so I downloaded the header and manually added to openfx-misc:
https://www.khronos.org/registry/khronos_headers.zip

Then, changed the line46 of to ColorLookup.cpp:
#include "../khronos_headers/GL/glext.h"

The compiler can find glext.h now, but it leads to this:
![unknown](https://user-images.githubusercontent.com/61306261/75007909-27292400-543c-11ea-8c48-d0090dea4ce3.png)

Some threads suggest that I need OpenGL 1.2 or higher but installing OpenGL 4.7 driver didn't help.
I also downloaded pre-compiled Mesa3D library (https://downloads.fdossena.com/Projects/Mesa3D/Builds/index.php)
then added as linker's additional dependency but I get the same LNK2001 error. Any help?

**Comment by devernay** [comment]
Vcxproj files are outdated and should be removed.
Use cmake to build instead. See .appveyor.yml file for details on how we build the VS-compiled binaries.

**Comment by yueda1984** [comment]
> Use cmake to build instead. See .appveyor.yml file for details on how we build the VS-compiled binaries.

Thank you for the instruction. I followed the yml file to build the vcxproj for VS2019 first with CMake 3.17.0-rc1 which returned an error:
`cd C:\Users\Admin\Documents\openfx-misc\build
set arch= Win64
set GENERATOR="Visual Studio 16 2019%arch%"
cmake .. -G %GENERATOR% -DCMAKE_INSTALL_PREFIX="c:/Users/Admin/Documents/openfx-misc/install"
CMake Error: Could not create named generator Visual Studio 16 2019 Win64`

But building for VS2013 worked. I opened generated build/OpenFXMisc.sln then built INSTALL.
Misc.ofx.bundle was built successfully but CImg.ofx.bundle was failed because of missing "openfx-misc/CImg/CImg.h".

**Comment by devernay** [comment]
the appveyor script downloads CImg.h and inpaint.h

**Comment by yueda1984** [comment]
Thank you devernay! After adding the 2 headers to the correct folder. I was able to build  CImg.ofx.bundle successfully. I still want to build some plugins separately but apparently there is https://github.com/NatronGitHub/openfx-misc/issues/2 so I will continue there.
