### ISSUE TITLE
Visual Studio could not find PluginRegistrationCombined.cpp and Noise.cpp also openfx

### ISSUE THREAD

**Issue by EsmeraldaQuintero** [NatronGitHub/openfx-misc#71]
Hello!

I'm cloning the `NatronGitHub/openfx-misc` and its dependencies `NatronGitHub/openfx` and `NatronGitHub/openfx-supportext`

But the current `openfx-misc\Misc\Misc.sln` doesn't work. I added at the include paths the `$(SourceDir)..` but it still isn't working. The `Noise/Noise.cpp` and `PluginRegistrationCombined.cpp` are missing

**Comment by rodlie** [comment]
Unsure if the sln file is supported, I recommend using CMake.

**Comment by devernay** [comment]
These files are here for convenience but not maintained. Feel free to fix these and submit a PR, or build using cmake, as it is done on appveyor: https://github.com/NatronGitHub/openfx-misc/blob/master/.appveyor.yml#L114
