### ISSUE TITLE
Vegas Pro 15 crashes when trying to use Rectangle OFX plugin

### ISSUE THREAD

**Issue by anavtor** [NatronGitHub/openfx-misc#75]
Vegas Pro 15 crashes when I try using Rectangle OFX plugin. 
The issue is in GeneratorPlugin ctor when calling beginEditBlock (ofxsGenerator.cpp line #187). I suppose the method should not be called from inside of createInstance action.
Commenting out the beginEditBlock and endEditBlock helps.

**Comment by devernay** [comment]
that's a good catch! thank you very much! sorry that I didn't see this issue when you submitted it @anavtor
