### ISSUE TITLE
How to change outputClip‘s framerate?

### ISSUE THREAD

**Issue by nothingtobenamed** [NatronGitHub/openfx-misc#88]
It seems that function clipPreferences.setOutputFrameRate() could setting output frame rate to any rate, example double.But parameter kOfxImageEffectPropSetableFrameRate is readonly, and host also can't set it.Could you please tell me how to change the output frame rate?

**Comment by devernay** [comment]
see https://openfx.readthedocs.io/en/doc/Reference/ofxClipPreferences.html#specifying-frame-rates

kOfxImageEffectPropSetableFrameRate is a host property that says whether the host allows to set the output frame rate

[kOfxImageEffectPropFrameRate](https://openfx.readthedocs.io/en/doc/Reference/ofxPropertiesReference.html#c.kOfxImageEffectPropFrameRate) is the property set on the output clip by setOutputFrameRate().

Note that this will only change the framerate property on the output clip. So for example if the input is 30fps and you set the output framerate to 60fps, then the output will have the same frames as the input, but will play twice faster.

This is not the same thing as retimining, where you would interpolate the input frames to play the same clip at twice the framerate. For this you'll need a plugin such as [Twixtor by Re:Vision Effects](https://revisionfx.com/products/twixtor/)

**Comment by devernay** [comment]
Note that Natron supports setting the output framerate, and you can test this with the NoOp plugin:
![image](https://user-images.githubusercontent.com/3778071/187305945-78700528-3184-45b6-9015-726fdc44820b.png)
