### ISSUE TITLE
failed build in mac

### ISSUE THREAD

**Issue by juneleung** [NatronGitHub/openfx-misc#90]
I try to build it in mac but looks missing some files, where to get these files or any steps I missed, thanks.
Though I make a dir named Darwin-64-debug and Darwin-64-release but still does not works.

`
cd openfx-misc
make BITS=64 CONFIG=release -j4         
                   
(cd Misc && /Applications/Xcode.app/Contents/Developer/usr/bin/make - --jobserver-fds=3,4 -j)
(cd Shadertoy && /Applications/Xcode.app/Contents/Developer/usr/bin/make - --jobserver-fds=3,4 -j)
(cd CImg && /Applications/Xcode.app/Contents/Developer/usr/bin/make - --jobserver-fds=3,4 -j)
make[1]: *** No rule to make target `Darwin-64-release/ofxsThreadSuite.o', needed by `Darwin-64-release/Shadertoy.ofx'.  Stop.
make: *** [Shadertoy] Error 2
make: *** Waiting for unfinished jobs....
make[1]: *** No rule to make target `Darwin-64-release/ofxsThreadSuite.o', needed by `Darwin-64-release/CImg.ofx'.  Stop.
make: *** [CImg] Error 2
make[1]: *** No rule to make target `Darwin-64-release/ofxsThreadSuite.o', needed by `Darwin-64-release/Misc.ofx'.  Stop.
make: *** [Misc] Error 2
`

**Comment by juneleung** [comment]
mac OS 11.6.8, Intel Core, xcode Version 13.0 (13A233),

**Comment by devernay** [comment]
https://github.com/NatronGitHub/openfx-misc#getting-the-sources-from-github

**Comment by devernay** [comment]
Don't forget to pull the submodules
